### ISSUE TITLE
WIN无法运行

### ISSUE THREAD

**Issue by whitesharks** [spkiddai/rad_xray_burplog#1]
Traceback (most recent call last):
  File "D:\rad_xray_burplog-main\main.py", line 11, in <module>
    from tool_run import tool_run
  File "D:\rad_xray_burplog-main\tool_run.py", line 12, in <module>
    import yaml
ModuleNotFoundError: No module named 'yaml'

**Comment by spkiddai** [comment]
Hi，白帽子，多谢使用。


程序报错已经很明显告诉你，未安装yaml模块。


使用命令 pip install PyYAML 进行安装。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "spkiddai/rad_xray_burplog"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年5月12日(星期三) 下午2:18
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[spkiddai/rad_xray_burplog] WIN无法运行 (#1)





 
Traceback (most recent call last):
 File "D:\rad_xray_burplog-main\main.py", line 11, in 
 from tool_run import tool_run
 File "D:\rad_xray_burplog-main\tool_run.py", line 12, in 
 import yaml
 ModuleNotFoundError: No module named 'yaml'
